### PR TITLE
Terraform upgrade to v0.12

### PR DESCRIPTION
**Pull request by yupwei68**

### CODE REVIEW

**Review by allengeer — APPROVED** [review]
Looks good to me. Removes all interpolation and map type issues with v.12

**Comment by robertoandrade** [comment]
can this be merged in? is there anything preventing it other than approvals?

**Comment by lonegunmanb** [comment]
Hi @robertoandrade, thanks for asking, this module hasn't been maintained for a long time, and we've launched a project named [Azure Verified Module](https://github.com/Azure/terraform-azure-modules). If you're using this module we can make it a verified module, it would include all changes inside this pr.

Are you using this module now?

**Comment by robertoandrade** [comment]
yes, we're actually forking it to to do some additional modifications and fixes we need for our own project. Looking forward to seeing these modules get some love from MS, especially since the Terraform provide has been moving forward and keeping up to date to current standards and the overall vision of terraform and IaC in general.

**Comment by lonegunmanb** [comment]
Thanks for the reply @robertoandrade, would you please share your fork repo with us so we can study what kind of modifications you've made? Once we start the work on this legacy module, I'd like to keep back compatible with your code if it's possible. I cannot guarantee you a timeline, but what I can promise is, I personally won't give up a module as long as we do have users who're using it.

**Comment by lonegunmanb** [comment]
I'm closing this pr since #22 has been merged. More prs are coming to bring more patches and features to this module.

**Pull request closed without merging**
